selenium-hub:
  image: selenium/hub
  container_name: selenium-hub
  ports:
    - "4444:4444"
  environment:
    - GRID_TIMEOUT=15
    - GRID_BROWSER_TIMEOUT=15
    - GRID_MAX_SESSION=2

chrome:
  image: selenium/node-chrome
  links: 
    - selenium-hub
  environment:
    - HUB_HOST=selenium-hub
    - HUB_PORT=4444
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
    - SCREEN_DEPTH=24

firefox:
  image: selenium/node-firefox
  links: 
    - selenium-hub
  environment:
    - HUB_HOST=selenium-hub
    - HUB_PORT=4444
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
    - SCREEN_DEPTH=24